# fly.toml app configuration file generated for chatwoot-odmqag on 2026-05-14T13:59:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chatwoot-odmqag'
primary_region = 'lhr'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[processes]
  app = './bin/rails server'
  sidekiq = 'bundle exec sidekiq'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
